# Generated by Django 4.0.3 on 2022-04-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='')),
                ('email', models.CharField(max_length=250)),
                ('phone', models.IntegerField(max_length=11)),
                ('birthdate', models.DateTimeField(verbose_name='')),
            ],
        ),
    ]
