# Generated by Django 4.0.3 on 2022-04-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='birthdate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='signup',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
