# Generated by Django 4.0.3 on 2022-04-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_signup_birthdate_alter_signup_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
