# Generated by Django 4.0.3 on 2022-04-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_signup_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='fullname',
            field=models.CharField(default='', max_length=250),
        ),
    ]
