# Generated by Django 4.0.3 on 2022-04-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_signup_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='fullname',
            new_name='login',
        ),
    ]
